version: octopus

mon:
- node1
- node2
- node3

mgr:
- node1

mds:
- node1
- node2

osd:
  hosts:
  - node1
  - node2
  - node3
  - node4
  conf:
    disk: /dev/nvmen01p4

fs:
  path: /mnt/cephfs
  client_fs: cephfs
  data_pool: cephfs_data
  metadata_pool: cephfs_metadata
  data_pool_pg_count: 16
  metadata_pool_pg_count: 16
