version: octopus
public_network: 10.10.1.0/16

admin:
- node0

mon:
- node1
- node2
- node3

mgr:
- node1

mds:
- node1
- node2

osd:
  hosts:
  - node1
  - node2
  - node3
  - node4
  conf:
    type: bluestore
    size: 50GB
    disk: /dev/nvmen01p4
